# -*- coding: utf-8 -*-
"""Sales_Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y79sLCKYdx9zzuvwx0Qhenm7R5xkj00X
"""

import numpy as np
import pandas as pd

df = pd.read_excel("Sales_Data.xlsx", sheet_name='Raw_Data')

#Quick Inspection
print('\n-----Shape of the excel file')
print(df.shape)
print('\n-----First 5 rows')
print(df.head())
print(df.info())
print(df.dtypes)
print(df.describe())

# Revenue by Region (matches your Excel pivot table)
revenue_by_region = df.groupby('Region')['Revenue'].agg(['sum', 'mean', 'count'])
revenue_by_region.columns = ['Total_Revenue', 'Average_Order_Count', 'Total_Orders']
revenue_by_region = revenue_by_region.sort_values(by= 'Total_Revenue', ascending=False)

print('\n--- Revenue by Region---\n')
print(revenue_by_region)

cross_tab = pd.crosstab(
    df['Region'],
    df['Category'],
    values = df['Revenue'],
    aggfunc = 'sum',
    margins = True,
    margins_name = 'Grand_Total'
)

print('\n---- Cross Tabulation-----')
print(cross_tab.round(2))

# Recreating SQL Monthly Trend
monthly_trend = df.groupby(df['OrderDate'].dt.to_period('M'))['Revenue'].agg(['sum', 'mean', 'count'])
monthly_trend.columns = ['Total_Revenue', 'Average_Revenue', 'Total_Orders']
print("\n--- Monthly Revenue ---")
print(monthly_trend)

# Build Visualizations
# Chart 1: Revenue by Region (matches your Excel chart)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
revenue_by_region['Total_Revenue'].plot(kind='bar', color='steelblue')
plt.title('Total Revenue by Region', fontsize=14, fontweight='bold')
plt.xlabel('Region')
plt.ylabel('Revenue ($)')
plt.xticks(rotation=0)
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig('revenue_by_region.png', dpi=300)
plt.show()

plt.figure(figsize=(10,6))
monthly_trend.plot(kind='line', marker='o', linewidth=2)
plt.title('Monthly Revenue Trend', fontsize=14, fontweight='bold')
plt.xlabel('Region')
plt.ylabel('Revenue ($)')
plt.xticks(rotation=0)
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig('monthly_trend.png', dpi=300)
plt.show()
'''

'''

# Chart 3: Category Breakdown (new — not in Excel or SQL)
plt.figure(figsize=(10,6))
category_revenue = df.groupby('Category')['Revenue'].sum().sort_values(ascending=False)
category_revenue.plot(kind='barh', color='coral')
plt.title('Revenue_by_Category', fontsize=14, fontweight='bold')
plt.xlabel('Revenue ($)')
plt.tight_layout()
plt.savefig('Revenue_by_Category.png', dpi=300)
plt.show()

# Replicating SQL JOIN in Python
# Create the regions DataFrame (equivalent to your SQL regions table)
regions_df = pd.DataFrame({
    'Region': ['North', 'South', 'East', 'West'],
    'Manager': ['Alice Johnson', 'Bob Smith', 'Carol White', 'David Brown'],
    'Target_Revenue': [150000, 120000, 180000, 160000]
})

# Merge with sales data (equivalent to SQL JOIN)
merged = df.groupby('Region')['Revenue'].sum().reset_index()
merged = merged.merge(regions_df, on='Region')

# Calculate performance metrics
merged['Percentage_of_Target'] = round((merged['Revenue'] / merged['Target_Revenue']) * 100, 2)

# Multiple WHEN conditions (equivalent to your SQL CASE)
def performance_status(row):
  if row['Revenue'] >= row['Target_Revenue']:
    return 'Met Target'
  else:
    return 'Target Not Met'

merged['Performance_Status'] = merged.apply(performance_status, axis=1)

print("\n--- Performance vs Target ---")
print(merged[['Region', 'Manager', 'Revenue', 'Target_Revenue', 'Percentage_of_Target', 'Performance_Status']])
'''
print(merged[['Region', 'Manager', 'Revenue', 'Target_Revenue', 'Percentage_of_Target', 'Performance_Status']])
'''

# Exporting Everything
# Save all results to one Excel file with multiple sheets

with pd.ExcelWriter('Python_Analysis_Result.xlsx') as writer:
  revenue_by_region.to_excel(writer, sheet_name='By_Region')
  cross_tab.to_excel(writer, sheet_name='Cross_Tab')
  monthly_trend.to_excel(writer, sheet_name='Monthly_Trend')
  merged.to_excel(writer, sheet_name='Performance_vs_Target')
  category_revenue.to_excel(writer, sheet_name='By_Category')

print("\n✓ All analysis exported to 'Python_Analysis_Results.xlsx'")

